// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Movable, MovableTableId } from "./tables/Movable.sol";
import { GameState, GameStateTableId } from "./tables/GameState.sol";
import { Score, ScoreTableId } from "./tables/Score.sol";
import { Matrix, MatrixTableId } from "./tables/Matrix.sol";
